---

- name: Terminal | Clone powerlevel10k repository
  git:
    repo: "{{ powerlevel10k_git }}"
    dest: "{{ home_directory }}/powerlevel10k"
    depth: 1

- name: Terminal | Install zsh
  become: yes
  apt:
    name: zsh
    state: present

- name: Terminal | Change shell to zsh
  become: yes
  shell:
    cmd: "chsh -s $(which zsh)"

- name: Terminal | Copy powerlevel10k configuration
  copy:
    src: p10k.zsh
    dest: "{{ home_directory }}/.p10k.zsh"

- name: Terminal | Copy zshrc configuration
  copy:
    src: zshrc
    dest: "{{ home_directory }}/.zshrc"

- name: Terminal | Get default profile (XFCE Terminal)
  shell:
    cmd: "xfconf-query -c xfce4-terminal -p /general/DefaultProfile"
  register: default_profile

- name: Terminal | Set custom command for XFCE Terminal profile
  shell:
    cmd: "xfconf-query -c xfce4-terminal -p /profiles/{{ default_profile.stdout.strip() }}/use-custom-command -s true"
  when: default_profile.stdout is defined

- name: Terminal | Set custom command (zsh) for XFCE Terminal profile
  shell:
    cmd: "xfconf-query -c xfce4-terminal -p /profiles/{{ default_profile.stdout.strip() }}/custom-command -s 'zsh'"
  when: default_profile.stdout is defined

- name: Terminal | Set transparency settings for XFCE Terminal profile
  shell:
    cmd: "xfconf-query -c xfce4-terminal -p /profiles/{{ default_profile.stdout.strip() }}/use-transparent-background -s true"
  when: default_profile.stdout is defined

- name: Terminal | Set transparency percentage for XFCE Terminal profile
  shell:
    cmd: "xfconf-query -c xfce4-terminal -p /profiles/{{ default_profile.stdout.strip() }}/background-transparency-percent -s 5"
  when: default_profile.stdout is defined
